publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: position_trajectory_controller

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.0, -1.571, 0.758, -0.758, 0.758, 0.0]
    pos2: [0.0, -1.571, 1.571, 0.0, 1.571, 0.0]
    pos3: [0.0, -1.571, 2.329, 0.758, 0.758, 0.0]
    pos4: [0.0, -1.571, 1.571, 0.0, 1.571, 0.0]

    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
